# Generated by Django 3.2 on 2021-10-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='preInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Target', models.CharField(max_length=50)),
                ('PBS', models.CharField(max_length=50)),
                ('RT', models.CharField(max_length=50)),
            ],
        ),
    ]
