# Generated by Django 3.2 on 2021-12-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegsub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cookie_database_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ALLELEID', models.IntegerField(null=True)),
                ('PAM', models.CharField(max_length=5)),
                ('DIRECTION', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='cookie_databse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlleleID', models.IntegerField(null=True)),
                ('Type', models.CharField(max_length=50)),
                ('Chromosome', models.IntegerField(null=True)),
                ('Start', models.IntegerField(null=True)),
                ('Stop', models.IntegerField(null=True)),
                ('ReferenceAllele', models.CharField(max_length=5)),
                ('AlternateAllele', models.CharField(max_length=5)),
                ('Spacer', models.CharField(max_length=50)),
                ('PBS', models.CharField(max_length=10)),
                ('RT', models.CharField(max_length=20)),
                ('PAM', models.CharField(max_length=5)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='cookie_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Target', models.CharField(max_length=50)),
                ('PBS', models.CharField(max_length=50)),
                ('RT', models.CharField(max_length=50)),
                ('Efficiency', models.FloatField(null=True)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cookie_position_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAM', models.CharField(max_length=5)),
                ('CUT_SIZE', models.IntegerField(null=True)),
                ('MAX_PBS', models.IntegerField(null=True)),
                ('MAX_RT', models.IntegerField(null=True)),
                ('MIN_PBS', models.IntegerField(null=True)),
                ('MIN_RT', models.IntegerField(null=True)),
                ('number_show', models.IntegerField(null=True)),
                ('input_chr', models.CharField(max_length=100)),
                ('input_position', models.IntegerField(null=True)),
                ('input_pattern', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cookie_sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Target', models.CharField(max_length=50)),
                ('PBS', models.CharField(max_length=50)),
                ('RT', models.CharField(max_length=50)),
                ('Efficiency', models.FloatField(null=True)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cookie_sequence_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAM', models.CharField(max_length=5)),
                ('CUT_SIZE', models.IntegerField(null=True)),
                ('MAX_PBS', models.IntegerField(null=True)),
                ('MAX_RT', models.IntegerField(null=True)),
                ('MIN_PBS', models.IntegerField(null=True)),
                ('MIN_RT', models.IntegerField(null=True)),
                ('number_show', models.IntegerField(null=True)),
                ('input_sequence', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='preInfo',
        ),
    ]
