# Generated by Django 3.2 on 2022-05-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegsub', '0003_cookie_sequence_april_cookie_sequence_april_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie_sequence_april_index',
            name='MAX_DISGRNA',
            field=models.IntegerField(null=True),
        ),
    ]
