# Generated by Django 3.2 on 2022-05-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegsub', '0005_cookie_position_april_cookie_position_april_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='cookie_database_April',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlleleID', models.IntegerField(null=True)),
                ('Type', models.CharField(max_length=50)),
                ('GeneID', models.CharField(max_length=50)),
                ('GeneSymbol', models.CharField(max_length=50)),
                ('HGNC_ID', models.IntegerField(null=True)),
                ('Chromosome', models.IntegerField(null=True)),
                ('Start', models.IntegerField(null=True)),
                ('Stop', models.IntegerField(null=True)),
                ('ReferenceAllele', models.CharField(max_length=5)),
                ('AlternateAllele', models.CharField(max_length=5)),
                ('Spacer', models.CharField(max_length=50)),
                ('PBS', models.CharField(max_length=10)),
                ('RT', models.CharField(max_length=20)),
                ('EditToNickDistance', models.IntegerField(null=True)),
                ('sgRNASpacer', models.CharField(max_length=50)),
                ('NickToNickDistance', models.IntegerField(null=True)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='cookie_database_April_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryType', models.CharField(max_length=50)),
                ('queryItem', models.IntegerField(null=True)),
                ('PAM', models.CharField(max_length=15)),
                ('DIRECTION', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
    ]
