# Generated by Django 3.2.5 on 2023-06-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unique_id',
            fields=[
                ('UID', models.CharField(max_length=17, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='cookie_sequence_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAM', models.CharField(max_length=5)),
                ('CUT_SIZE', models.IntegerField(null=True)),
                ('MAX_PBS', models.IntegerField(null=True)),
                ('MAX_RT', models.IntegerField(null=True)),
                ('MIN_PBS', models.IntegerField(null=True)),
                ('MIN_RT', models.IntegerField(null=True)),
                ('TOP_N', models.IntegerField(null=True)),
                ('GENOME', models.CharField(max_length=20)),
                ('MIN_DISGRNA', models.IntegerField(null=True)),
                ('MAX_DISGRNA', models.IntegerField(null=True)),
                ('HOMOLOGY', models.IntegerField(null=True)),
                ('SEQUENCE', models.CharField(max_length=100)),
                ('UID', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pegRNA.unique_id')),
            ],
        ),
        migrations.CreateModel(
            name='cookie_sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strand', models.CharField(max_length=2, null=True)),
                ('Spacer', models.CharField(max_length=50, null=True)),
                ('PAM', models.CharField(max_length=5, null=True)),
                ('PBS', models.CharField(max_length=50, null=True)),
                ('RT', models.CharField(max_length=50, null=True)),
                ('EditToNickDistance', models.IntegerField(null=True)),
                ('sgRNASpacer', models.CharField(max_length=50, null=True)),
                ('sgRNAPAM', models.CharField(max_length=50, null=True)),
                ('NickToNickDistance', models.IntegerField(null=True)),
                ('EditingScore', models.FloatField(null=True)),
                ('FID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pegRNA.unique_id')),
            ],
        ),
        migrations.CreateModel(
            name='cookie_position_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAM', models.CharField(max_length=5)),
                ('CUT_SIZE', models.IntegerField(null=True)),
                ('MAX_PBS', models.IntegerField(null=True)),
                ('MAX_RT', models.IntegerField(null=True)),
                ('MIN_PBS', models.IntegerField(null=True)),
                ('MIN_RT', models.IntegerField(null=True)),
                ('TOP_N', models.IntegerField(null=True)),
                ('GENOME', models.CharField(max_length=20)),
                ('MIN_DISGRNA', models.IntegerField(null=True)),
                ('MAX_DISGRNA', models.IntegerField(null=True)),
                ('HOMOLOGY', models.IntegerField(null=True)),
                ('Chromosome', models.CharField(max_length=100, null=True)),
                ('Position', models.IntegerField(null=True)),
                ('Pattern', models.CharField(max_length=50, null=True)),
                ('UID', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pegRNA.unique_id')),
            ],
        ),
        migrations.CreateModel(
            name='cookie_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strand', models.CharField(max_length=2)),
                ('Spacer', models.CharField(max_length=50, null=True)),
                ('PAM', models.CharField(max_length=5, null=True)),
                ('PBS', models.CharField(max_length=50, null=True)),
                ('RT', models.CharField(max_length=50, null=True)),
                ('EditToNickDistance', models.IntegerField(null=True)),
                ('sgRNASpacer', models.CharField(max_length=50, null=True)),
                ('sgRNAPAM', models.CharField(max_length=50, null=True)),
                ('NickToNickDistance', models.IntegerField(null=True)),
                ('EditingScore', models.FloatField(null=True)),
                ('FID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pegRNA.unique_id')),
            ],
        ),
        migrations.CreateModel(
            name='cookie_opedvar_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryType', models.CharField(max_length=50)),
                ('queryItem', models.CharField(max_length=50)),
                ('PAM', models.CharField(max_length=15)),
                ('GENOME', models.CharField(max_length=20)),
                ('DIRECTION', models.CharField(max_length=15)),
                ('UID', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pegRNA.unique_id')),
            ],
        ),
        migrations.CreateModel(
            name='cookie_opedvar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlleleID', models.IntegerField(null=True)),
                ('Type', models.CharField(max_length=50, null=True)),
                ('GeneID', models.CharField(max_length=50, null=True)),
                ('GeneSymbol', models.CharField(max_length=50, null=True)),
                ('HGNC_ID', models.IntegerField(null=True)),
                ('Chromosome', models.IntegerField(null=True)),
                ('Start', models.IntegerField(null=True)),
                ('Stop', models.IntegerField(null=True)),
                ('ReferenceAllele', models.CharField(max_length=5, null=True)),
                ('AlternateAllele', models.CharField(max_length=5, null=True)),
                ('Strand', models.CharField(max_length=2, null=True)),
                ('Spacer', models.CharField(max_length=50)),
                ('PBS', models.CharField(max_length=10, null=True)),
                ('RT', models.CharField(max_length=20, null=True)),
                ('EditToNickDistance', models.IntegerField(null=True)),
                ('sgRNASpacer', models.CharField(max_length=50, null=True)),
                ('NickToNickDistance', models.IntegerField(null=True)),
                ('FID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pegRNA.unique_id')),
            ],
        ),
    ]
